@startuml

participant FormUI
participant Post
participant PostScheduler
participant FacebookService

FormUI -> Post: Create a new Post object
Post --> FormUI: Return Post object
FormUI -\\ PostScheduler: Schedule Post for dispatch

group Task.Delay (ms)
    PostScheduler -> PostScheduler: ScheduleAt
end

PostScheduler -> Post: Trigger dispatch event
Post -> FacebookService: Post Status

@enduml
